import ilm from "../assets/icons/univer.svg?react";
import univer from "../assets/icons/ilm.svg?react";
import qabul from "../assets/icons/qabul.svg?react";
import styled from "styled-components";

const Icons = styled.div``;
Icons.Ilm = styled(ilm)``;
Icons.Qabul = styled(qabul)``;
Icons.Univer = styled(univer)``;

export const sidebar = [
  { id: 1, content: "Yangiliklar", isSelect: false, path: "/news" },
  { id: 2, content: "E’lonlar", isSelect: false, path: "/announcement" },
  { id: 3, content: "Universitet", isSelect: true },
  { id: 4, content: "Tal’im", isSelect: true },
  { id: 5, content: "Ilm-fan", isSelect: true },
  { id: 6, content: "Xalqaro aloqalar", isSelect: true },
  { id: 7, content: "Ma’naviyat", isSelect: true },
  { id: 8, content: "Qabul", isSelect: true },
  { id: 9, content: "Bitiruvchi", isSelect: true },
];

// export const hoverContent = [
//   {
//     id: 3,
//     icon: <Icons.Univer />,
//     title: "Universitet",
//     desc: "Toshkent davlat transport universiteti transport sohasi uchun oliy maʼlumotli mutaxassislar va ilmiy kadrlarni tayyorlash, qayta tayyorlash va ularning malakasini oshirish boʼyicha tayanch oliy taʼlim muassasasi hisoblanadi.",
//     links: [
//       { id: "-1", title: "Biz haqimizda" },
//       { id: 0, path: "", link: "Strategik rivojlantirish dasturi" },
//       { id: 1, path: "", link: "Barqaror rivojlanish maqsadlari" },
//       { id: 2, path: "", link: "Tarix" },
//       { id: 3, path: "", link: "Asosiy  ma'lumotlar" },
//       { id: 4, path: "", link: "Me’yoriy hujjatlar" },
//       { id: 5, path: "", link: "Moliyaviy hisobotlar" },
//       { id: 6, path: "", link: "Universitet nizomi" },
//       { id: 7, path: "", link: "Korrupsiyaga qarshi kurashish" },
//       { id: 8, path: "", link: "Gender tenglik" },
//       { id: 9, title: "Tuzilma va boshqaruv organlari" },
//       { id: 10, path: "", link: "Tashkiliy tuzilma" },
//       { id: 11, path: "", link: "Kuzatuv kengashi" },
//       { id: 12, path: "", link: "Universitet kengashi" },
//       { id: 13, path: "", link: "Jamoatchilik kengashi" },
//       { id: 14, path: "/rectorat", link: "Rektorat" },
//       { id: 15, path: "/faculties", link: "Fakultetlar" },
//       { id: 16, path: "", link: "Kafedralar" },
//       { id: 17, path: "", link: "Boshqarma va bo'limlar" },
//       { id: 18, path: "/centers", link: "Markazlar" },
//       { id: 19, path: "/musem", link: "Muzey " },
//       { id: 20, path: "/sport", link: "Sport majmusi" },
//     ],
//   },
//   {
//     id: 4,
//     icon: <Icons.Univer />,
//     title: "Taʼlim",
//     desc: "Universitet transport ta’lim sohasi bо‘yicha Respublikada tayanch oliy ta’lim muassasasi hisoblanadi. Bugungi kunda universitetda kredit-modul tizimi asosida aviatsiya transporti, temir yо‘l transporti, avtomobil transporti hamda qurilish sohalariga 60 ta bakalavriat ta’lim yо‘nalishlari va 41 ta magistratura mutaxassisligi bо‘yicha kadrlar tayyorlanmoqda.",
//     links: [
//       { id: 0, title: "Boshqarma va bo'limlar" },
//       { id: 1, path: "", link: "O‘quv-uslubiy boshqarma" },
//       {
//         id: 2,
//         path: "",
//         link: "Masofaviy taʼlim tashkil etish va rivojlantirish markazi",
//       },
//       { id: 3, path: "", link: "Raqamli ta‘lim texnologiyalari markazi" },
//       { id: 4, path: "/arm", link: "Axborot-resurs markazi" },
//       { id: 5, path: "", link: "Magistratura bo‘limi" },
//       { id: 6, path: "", link: "Tahririy nashriyot va poligrafiya bo‘limi" },
//       { id: 7, path: "", link: "Sirtqi bo‘lim" },
//       { id: 8, path: "", link: "Marketing va talabalar amaliyoti bo‘limi" },
//       { id: 9, title: "Oliy ta'lim" },
//       { id: 10, path: "", link: "Malaka talablari" },
//       { id: 11, path: "", link: "O'quv rejalar" },
//       { id: 12, path: "", link: "Ta’lim darajasi va ta’lim shakllari" },
//       { id: 13, path: "", link: "Ta’lim yо‘nalishlari" },
//       { id: 14, path: "", link: "Ta’lim mutaxassisliklari" },
//       { id: 15, path: "", link: "Stipendiyalar" },
//       { id: 16, path: "", link: "Davlat imtihonlari" },
//       { id: 17, path: "", link: "Yozgi maktab" },
//       { id: 18, title: "Qo'shimcha ta'lim" },
//       { id: 19, path: "", link: "Malaka oshirish va qayta tayyorlash markazi" },
//       { id: 20, title: "О‘rta va professional ta’lim" },
//       { id: 21, path: "", link: "Texnikumlar" },
//       { id: 22, path: "", link: "Akademik litsey" },
//     ],
//   },
//   {
//     id: 5,
//     icon: <Icons.Ilm />,
//     title: "Ilm-fan",
//     desc: "Doimiy oʻsish imkoniyatidan foydalaning. Toshkent davlat transport universiteti илмий-тадқиқот департаменти iqtidorli talabalar, yosh olimlar va universitet professor-o‘qituvchilariga ilmiy-tadqiqot ishlarini olib borishda doimo yordam berib kelmoqda.",
//     links: [
//       { id: 0, title: "Bo'limlar" },
//       {
//         id: 1,
//         path: "",
//         link: "Ilmiy tadqiqotlar, innovatsiyalar va ilmiy-pedagogik kadrlar tayyorlash bo’limi",
//       },
//       {
//         id: 2,
//         path: "",
//         link: "Ilmiy – innovatsion ishlanmalarni tijoratlashtirish bo’limi",
//       },
//       {
//         id: 3,
//         path: "",
//         link: "Iqtidorli talabalarning ilmiy – tadqiqot faoliyatini tashkil etish bo’limi",
//       },
//       {
//         id: 4,
//         path: "",
//         link: "O’z-o’zini moliyalashtiradigan ilmiy-tadqiqot bo’limi",
//       },
//       { id: 5, path: "", link: "Xalqaro reytinglar bilan ishlash bo'limi" },
//       { id: 6, title: "Xalqaro dastur va reytinglar" },
//       { id: 7, path: "", link: "O’zbekiston OTM larining milliy reytingi" },
//       { id: 8, path: "", link: "Quacquarelli Symonds" },
//       { id: 9, path: "", link: "Times Higher Education" },
//       { id: 10, title: "Jurnallar" },
//       {
//         id: 11,
//         path: "",
//         link: "Transport vositalari va yo’llari ilmiy jurnali",
//       },
//       {
//         id: 12,
//         path: "",
//         link: "Temir yo’l transporti: dolzarb masalalar va innovatsiyalar",
//       },
//       { id: 13, title: "Ilmiy kengashlar" },
//       { id: 14, path: "", link: "Ilmiy darajalar beruvchi kengashlar" },
//       { id: 15, path: "", link: "Mavjud ixtisosliklar" },
//       { id: 16, path: "", link: "Malakaviy imtihonlar" },
//       { id: 17, path: "", link: "Doktorantura" },
//       { id: 18, title: "Ko‘rsatkichlar" },
//       {
//         id: 19,
//         path: "",
//         link: "Universiteti olimlarining ilmiy faoliyat natijalari",
//       },
//       { id: 20, path: "", link: "Maqolalar" },
//       { id: 21, path: "", link: "Patentlar" },
//       { id: 22, path: "", link: "Monografiyalar" },
//     ],
//   },
//   {
//     id: 6,
//     icon: <Icons.Qabul />,
//     title: "Xalqaro aloqalar",
//     desc: "Chet el davlatlar bilan ta’lim sohasida tarjiba almashish, maqsadida ko‘plab dasturlar orqali professor-o‘qituvchilar va talabalarni xorijiy davlatlarda amaliyot o‘tash hamda grant asosida o‘qish imkoniyatlarini yaratilmoqda.",
//     links: [
//       { id: 0, title: "Boshqarma va bo'limlar" },
//       { id: 1, path: "", link: "Xalqaro hamkorlik boshqarmasi" },
//       {
//         id: 2,
//         path: "",
//         link: "Akademik mobillik, xorijiy grantlar va institutlar bilan ishlash bo'limi",
//       },
//       {
//         id: 3,
//         path: "",
//         link: "Xalqaro ta’lim dasturlari bilan ishlash bo'limi",
//       },
//       { id: 4, path: "", link: "Xorij bilan hamkorlik markazi" },
//       { id: 5, path: "", link: "O‘zbekiston-Turkiya hamkorlik markazi" },
//       { id: 6, path: "", link: "“Language Club” xorijiy tillar markazi" },
//       { id: 7, title: "Faoliyat" },
//       { id: 8, path: "", link: "Amaldagi loyihalar" },
//       { id: 9, path: "", link: "Xalqaro hamkorlar" },
//       { id: 10, path: "", link: "Xorijiy talabalarga" },
//       { id: 11, path: "", link: "Jalb etilgan sarmoyalar va grantlar" },
//       { id: 12, path: "", link: "Xorijda malaka oshirish va ta’lim" },
//       { id: 13, path: "", link: "Work and Travel" },
//       { id: 14, path: "", link: "Erasmus" },
//     ],
//   },
//   {
//     id: 7,
//     icon: <Icons.Qabul />,
//     title: "Ma‘naviat",
//     desc: "Talabalarning bo‘sh vaqtlarini mazmunli tashkil etish, ularning iqtidorlarini ro‘yobga chiqarish va ko‘maklashish maqsadida turli tadbirlar, tanlovlar va loyihalar tashkil etib kelinmoqda.",
//     links: [
//       { id: 0, title: "Madaniy-ma’rifiy faoliya" },
//       { id: 1, path: "", link: "Ma’naviy-ma’rifiy tadbirlar" },
//       {
//         id: 2,
//         path: "",
//         link: "Yoshlar bilan ishlash, ma’naviyat va ma’rifat bо‘limi",
//       },
//       { id: 3, path: "", link: "To‘garak va klublar" },
//       { id: 4, path: "", link: "Tanlovlar, musobaqa va stipendiyalar" },
//       { id: 5, path: "", link: "Talabalar shaharchasi" },
//       { id: 6, path: "", link: "Muzey" },
//       { id: 7, path: "", link: "Psixologik Yordam Markazi" },
//       {
//         id: 8,
//         path: "",
//         link: "Talabalarni turar joy bilan ta'minlash ishlarini muvofiqlashtiruvchi bo‘lim",
//       },
//       { id: 9, path: "", link: "Talabalar hayotidan fotogalereya" },
//       { id: 10, path: "", link: "Maqsud Shayxzoda stipendiyasi" },
//       {
//         id: 11,
//         path: "",
//         link: "Universiteti odob-axloq kodeksi va ichki - tartib qoidalari",
//       },
//       { id: 12, title: "Jamoat birlashmalari" },
//       { id: 13, path: "", link: "Jamoatchilik kengashi" },
//       { id: 14, path: "", link: "Ma’naviyat va ma’rifat kengashi" },
//       {
//         id: 15,
//         path: "",
//         link: "Xotin-qizlar masalalari bo‘yicha maslahat-kengashi",
//       },
//       { id: 16, path: "", link: "Nuroniylar kengashi" },
//       { id: 17, path: "", link: "Talabalar kengashi" },
//       { id: 18, path: "", link: "Yoshlar ittifoqi boshlang‘ich tashkiloti" },
//       { id: 19, path: "", link: "“Transportchilar” sport klubi" },
//     ],
//   },
//   {
//     id: 8,
//     icon: <Icons.Qabul />,
//     title: "Qabul komissiyasi",
//     desc: "Toshkent davlat transport universiteti transport sohasi uchun oliy maʼlumotli mutaxassislar va ilmiy kadrlarni tayyorlash, qayta tayyorlash va ularning malakasini oshirish boʼyicha tayanch oliy taʼlim muassasasi hisoblanadi.",
//     links: [
//       { id: 0, path: "", link: "Qabul komissiyasi tarkibi" },
//       {
//         id: 1,
//         path: "",
//         link: "Bakalavriatning kunduzgi ta'lim shakliga qabul",
//       },
//       { id: 2, path: "", link: "Bakalavriatning sirtqi ta'lim shakliga qabul" },
//       {
//         id: 3,
//         path: "",
//         link: "Bakalavriatning masofaviy ta'lim shakliga qabul",
//       },
//       { id: 4, path: "", link: "Magistraturaga qabul" },
//       { id: 5, path: "", link: "2 - va undan keyingi oliy ta'limga qabul" },
//       { id: 6, path: "", link: "Qo`shma ta`lim dasturlariga asosida qabul" },
//       { id: 7, path: "", link: "Xorijiy fuqorolar qabuli" },
//       { id: 8, path: "", link: "O'qishni tiklash" },
//       { id: 9, path: "", link: "Talabalar o'qishini ko'chirish" },
//       { id: 10, path: "", link: "Xalqaro ta'lim dasturlari" },
//       { id: 11, path: "", link: "Aloqa" },
//       {
//         id: 12,
//         path: "",
//         link: "Texnikumlarni muvaffaqiyatli tamomlagan abituriyentlar",
//       },
//     ],
//   },
//   {
//     id: 9,
//     icon: <Icons.Qabul />,
//     title: "BITIRUVCHI",
//     desc: "Bugungi kunda universitetning ko'plab bitiruvchilari O'zbekiston vazirliklari, idoralari va qonun chiqaruvchi organlarida rahbarlik lavozimlarini egallab, dunyoning yetakchi xalqaro tashkilotlari va yirik kompaniyalarida muvaffaqiyatli faoliyat yuritmoqdalar",
//     links: [
//       { id: 0, path: "", link: "Karyera markazi" },
//       { id: 1, path: "", link: "Bitiruvchilar assotsiatsiyasi" },
//       { id: 2, path: "", link: "Faxriy bitiruvchilar" },
//       { id: 3, path: "", link: "Bitiruvchilar to'g'risida ma'lumot" },
//     ],
//   },
// ];

export const hoverContent = [
  {
    id: 3,
    icon: <Icons.Univer />,
    title: "Universitet",
    desc: "Toshkent davlat transport universiteti transport sohasi uchun oliy maʼlumotli mutaxassislar va ilmiy kadrlarni tayyorlash, qayta tayyorlash va ularning malakasini oshirish boʼyicha tayanch oliy taʼlim muassasasi hisoblanadi.",
  },
  {
    id: 4,
    icon: <Icons.Univer />,
    title: "Taʼlim",
    desc: "Universitet transport ta’lim sohasi bо‘yicha Respublikada tayanch oliy ta’lim muassasasi hisoblanadi. Bugungi kunda universitetda kredit-modul tizimi asosida aviatsiya transporti, temir yо‘l transporti, avtomobil transporti hamda qurilish sohalariga 60 ta bakalavriat ta’lim yо‘nalishlari va 41 ta magistratura mutaxassisligi bо‘yicha kadrlar tayyorlanmoqda.",
    links: [
      { id: 0, path: "contact", link: "Contact" },
      { id: 1, path: "faq", link: "Faq" },
      { id: 2, path: "rector", link: "Rektorga murojat" },
      { id: 3, path: "scientific-center", link: "Limiy markaz" },
      { id: 4, path: "history", link: "Bizning tarix" },
      { id: 5, path: "sport", link: "Sport majmuasi" },
      { id: 6, path: "admisson", link: "Qabul komissiyasi" },
      { id: 7, path: "honorary", link: "Faxriy professor o‘qtuvchilar" },
      { id: 8, path: "centers", link: "Markazlar" },
      { id: 9, path: "404", link: "404" },
      { id: 10, path: "faculties", link: "Fakultetlar" },
      { id: 11, path: "news", link: "Yangiliklar" },
      { id: 12, path: "rectorat", link: "Rektorat" },
      { id: 13, path: "arm", link: "Axborot Resuslari markazi" },
      { id: 14, path: "galereya", link: "Galereya" },
      { id: 15, path: "departments", link: "Bo‘limlar va boshqarmalar" },
      {
        id: 16,
        path: "interactive-services",
        link: "Interaktiv xizmatlari",
      },
      {
        id: 17,
        path: "signup",
        link: "Registratsiya",
      },
      {
        id: 18,
        path: "signin",
        link: "Kirish",
      },
    ],
  },
  {
    id: 5,
    icon: <Icons.Ilm />,
    title: "Ilm-fan",
    desc: "Doimiy oʻsish imkoniyatidan foydalaning. Toshkent davlat transport universiteti илмий-тадқиқот департаменти iqtidorli talabalar, yosh olimlar va universitet professor-o‘qituvchilariga ilmiy-tadqiqot ishlarini olib borishda doimo yordam berib kelmoqda.",
  },
  {
    id: 6,
    icon: <Icons.Qabul />,
    title: "Xalqaro aloqalar",
    desc: "Chet el davlatlar bilan ta’lim sohasida tarjiba almashish, maqsadida ko‘plab dasturlar orqali professor-o‘qituvchilar va talabalarni xorijiy davlatlarda amaliyot o‘tash hamda grant asosida o‘qish imkoniyatlarini yaratilmoqda.",
  },
  {
    id: 7,
    icon: <Icons.Qabul />,
    title: "Ma‘naviat",
    desc: "Talabalarning bo‘sh vaqtlarini mazmunli tashkil etish, ularning iqtidorlarini ro‘yobga chiqarish va ko‘maklashish maqsadida turli tadbirlar, tanlovlar va loyihalar tashkil etib kelinmoqda.",
  },
  {
    id: 8,
    icon: <Icons.Qabul />,
    title: "Qabul komissiyasi",
    desc: "Toshkent davlat transport universiteti transport sohasi uchun oliy maʼlumotli mutaxassislar va ilmiy kadrlarni tayyorlash, qayta tayyorlash va ularning malakasini oshirish boʼyicha tayanch oliy taʼlim muassasasi hisoblanadi.",
  },
  {
    id: 9,
    icon: <Icons.Qabul />,
    title: "Manaviat",
    desc: "Bugungi kunda universitetning ko'plab bitiruvchilari O'zbekiston vazirliklari, idoralari va qonun chiqaruvchi organlarida rahbarlik lavozimlarini egallab, dunyoning yetakchi xalqaro tashkilotlari va yirik kompaniyalarida muvaffaqiyatli faoliyat yuritmoqdalar",
  },
];

export const umumiySidebar = [
  {
    id: 1,
    title: "Universitet",
    links: [
      { id: 1, title: "Biz haqimizda" },
      { id: 2, path: "", name: "- Strategik rivojlantirish dasturi" },
      { id: 3, path: "", name: "- Barqaror rivojlanish maqsadlari" },
      { id: 4, path: "", name: "- Tarix" },
      { id: 5, path: "", name: "- Asosiy ma'lumotlar" },
      { id: 6, path: "", name: "- Me’yoriy hujjatlar" },
      { id: 7, path: "", name: "- Moliyaviy hisobotlar" },
      { id: 8, path: "", name: "- Universitet nizomi" },
      { id: 9, path: "", name: "- Korrupsiyaga qarshi kurashish" },
      { id: 10, path: "", name: "- Gender tenglik" },
      { id: 11, title: "Tuzilma va boshqaruv organlari" },
      { id: 12, path: "", name: "- Tashkiliy tuzilma" },
      { id: 13, path: "", name: "- Kuzatuv Kengashi" },
      { id: 14, path: "", name: "- Universitet Kengashi" },
      { id: 15, path: "", name: "- Jamoatchilik kengashi" },
      { id: 16, path: "", name: "- Rektorat" },
      { id: 17, path: "", name: "- Fakultetlar" },
      { id: 18, path: "", name: "- Kafedralar" },
      { id: 19, path: "", name: "- Boshqarma va bo'limlar" },
      { id: 20, path: "", name: "- Markazlar" },
      { id: 21, path: "", name: "- Muzey" },
      { id: 22, path: "", name: "- Sport majmuasi" },
    ],
  },
  {
    id: 2,
    title: "Tal’im",
    links: [
      { id: 0, title: "Boshqarma va bo'limlar" },
      { id: 1, path: "", name: "O‘quv-uslubiy boshqarma" },
      {
        id: 2,
        path: "",
        name: "Masofaviy taʼlim tashkil etish va rivojlantirish markazi",
      },
      { id: 3, path: "", name: "Raqamli ta‘lim texnologiyalari markazi" },
      { id: 4, path: "/arm", name: "Axborot-resurs markazi" },
      { id: 5, path: "", name: "Magistratura bo‘limi" },
      { id: 6, path: "", name: "Tahririy nashriyot va poligrafiya bo‘limi" },
      { id: 7, path: "", name: "Sirtqi bo‘lim" },
      { id: 8, path: "", name: "Marketing va talabalar amaliyoti bo‘limi" },
      { id: 9, title: "Oliy ta'lim" },
      { id: 10, path: "", name: "Malaka talablari" },
      { id: 11, path: "", name: "O'quv rejalar" },
      { id: 12, path: "", name: "Ta’lim darajasi va ta’lim shakllari" },
      { id: 13, path: "", name: "Ta’lim yо‘nalishlari" },
      { id: 14, path: "", name: "Ta’lim mutaxassisliklari" },
      { id: 15, path: "", name: "Stipendiyalar" },
      { id: 16, path: "", name: "Davlat imtihonlari" },
      { id: 17, path: "", name: "Yozgi maktab" },
      { id: 18, title: "Qo'shimcha ta'lim" },
      { id: 19, path: "", name: "Malaka oshirish va qayta tayyorlash markazi" },
      { id: 20, title: "О‘rta va professional ta’lim" },
      { id: 21, path: "", name: "Texnikumlar" },
      { id: 22, path: "", name: "Akademik litsey" },
    ],
  },
  {
    id: 3,
    title: "Ilm-fan",
    links: [
      { id: 0, title: "Bo'limlar" },
      {
        id: 1,
        path: "",
        name: "Ilmiy tadqiqotlar, innovatsiyalar va ilmiy-pedagogik kadrlar tayyorlash bo’limi",
      },
      {
        id: 2,
        path: "",
        name: "Ilmiy – innovatsion ishlanmalarni tijoratlashtirish bo’limi",
      },
      {
        id: 3,
        path: "",
        name: "Iqtidorli talabalarning ilmiy – tadqiqot faoliyatini tashkil etish bo’limi",
      },
      {
        id: 4,
        path: "",
        name: "O’z-o’zini moliyalashtiradigan ilmiy-tadqiqot bo’limi",
      },
      { id: 5, path: "", name: "Xalqaro reytinglar bilan ishlash bo'limi" },
      { id: 6, title: "Xalqaro dastur va reytinglar" },
      { id: 7, path: "", name: "O’zbekiston OTM larining milliy reytingi" },
      { id: 8, path: "", name: "Quacquarelli Symonds" },
      { id: 9, path: "", name: "Times Higher Education" },
      { id: 10, title: "Jurnallar" },
      {
        id: 11,
        path: "",
        name: "Transport vositalari va yo’llari ilmiy jurnali",
      },
      {
        id: 12,
        path: "",
        name: "Temir yo’l transporti: dolzarb masalalar va innovatsiyalar",
      },
      { id: 13, title: "Ilmiy kengashlar" },
      { id: 14, path: "", name: "Ilmiy darajalar beruvchi kengashlar" },
      { id: 15, path: "", name: "Mavjud ixtisosliklar" },
      { id: 16, path: "", name: "Malakaviy imtihonlar" },
      { id: 17, path: "", name: "Doktorantura" },
      { id: 18, title: "Ko‘rsatkichlar" },
      {
        id: 19,
        path: "",
        name: "Universiteti olimlarining ilmiy faoliyat natijalari",
      },
      { id: 20, path: "", name: "Maqolalar" },
      { id: 21, path: "", name: "Patentlar" },
      { id: 22, path: "", name: "Monografiyalar" },
    ],
  },
  {
    id: 4,
    title: "Xalqaro aloqalar",
    links: [
      { id: 0, title: "Boshqarma va bo'limlar" },
      { id: 1, path: "", name: "Xalqaro hamkorlik boshqarmasi" },
      {
        id: 2,
        path: "",
        name: "Akademik mobillik, xorijiy grantlar va institutlar bilan ishlash bo'limi",
      },
      {
        id: 3,
        path: "",
        name: "Xalqaro ta’lim dasturlari bilan ishlash bo'limi",
      },
      { id: 4, path: "", name: "Xorij bilan hamkorlik markazi" },
      { id: 5, path: "", name: "O‘zbekiston-Turkiya hamkorlik markazi" },
      { id: 6, path: "", name: "“Language Club” xorijiy tillar markazi" },
      { id: 7, title: "Faoliyat" },
      { id: 8, path: "", name: "Amaldagi loyihalar" },
      { id: 9, path: "", name: "Xalqaro hamkorlar" },
      { id: 10, path: "", name: "Xorijiy talabalarga" },
      { id: 11, path: "", name: "Jalb etilgan sarmoyalar va grantlar" },
      { id: 12, path: "", name: "Xorijda malaka oshirish va ta’lim" },
      { id: 13, path: "", name: "Work and Travel" },
      { id: 14, path: "", name: "Erasmus" },
    ],
  },
  {
    id: 5,
    title: "Ma’naviyat",
    links: [
      { id: 0, title: "Madaniy-ma’rifiy faoliya" },
      { id: 1, path: "", name: "Ma’naviy-ma’rifiy tadbirlar" },
      {
        id: 2,
        path: "",
        name: "Yoshlar bilan ishlash, ma’naviyat va ma’rifat bо‘limi",
      },
      { id: 3, path: "", name: "To‘garak va klublar" },
      { id: 4, path: "", name: "Tanlovlar, musobaqa va stipendiyalar" },
      { id: 5, path: "", name: "Talabalar shaharchasi" },
      { id: 6, path: "", name: "Muzey" },
      { id: 7, path: "", name: "Psixologik Yordam Markazi" },
      {
        id: 8,
        path: "",
        name: "Talabalarni turar joy bilan ta'minlash ishlarini muvofiqlashtiruvchi bo‘lim",
      },
      { id: 9, path: "", name: "Talabalar hayotidan fotogalereya" },
      { id: 10, path: "", name: "Maqsud Shayxzoda stipendiyasi" },
      {
        id: 11,
        path: "",
        name: "Universiteti odob-axloq kodeksi va ichki - tartib qoidalari",
      },
      { id: 12, title: "Jamoat birlashmalari" },
      { id: 13, path: "", name: "Jamoatchilik kengashi" },
      { id: 14, path: "", name: "Ma’naviyat va ma’rifat kengashi" },
      {
        id: 15,
        path: "",
        name: "Xotin-qizlar masalalari bo‘yicha maslahat-kengashi",
      },
      { id: 16, path: "", name: "Nuroniylar kengashi" },
      { id: 17, path: "", name: "Talabalar kengashi" },
      { id: 18, path: "", name: "Yoshlar ittifoqi boshlang‘ich tashkiloti" },
      { id: 19, path: "", name: "“Transportchilar” sport klubi" },
    ],
  },
  {
    id: 6,
    title: "Qabul",
    links: [
      { id: 0, path: "", name: "Qabul komissiyasi tarkibi" },
      {
        id: 1,
        path: "",
        name: "Bakalavriatning kunduzgi ta'lim shakliga qabul",
      },
      { id: 2, path: "", name: "Bakalavriatning sirtqi ta'lim shakliga qabul" },
      {
        id: 3,
        path: "",
        name: "Bakalavriatning masofaviy ta'lim shakliga qabul",
      },
      { id: 4, path: "", name: "Magistraturaga qabul" },
      { id: 5, path: "", name: "2 - va undan keyingi oliy ta'limga qabul" },
      { id: 6, path: "", name: "Qo`shma ta`lim dasturlariga asosida qabul" },
      { id: 7, path: "", name: "Xorijiy fuqorolar qabuli" },
      { id: 8, path: "", name: "O'qishni tiklash" },
      { id: 9, path: "", name: "Talabalar o'qishini ko'chirish" },
      { id: 10, path: "", name: "Xalqaro ta'lim dasturlari" },
      { id: 11, path: "", name: "Aloqa" },
      {
        id: 12,
        path: "",
        name: "Texnikumlarni muvaffaqiyatli tamomlagan abituriyentlar",
      },
    ],
  },
  {
    id: 7,
    title: "Bitiruvchi",
    links: [
      { id: 0, path: "", name: "Karyera markazi" },
      { id: 1, path: "", name: "Bitiruvchilar assotsiatsiyasi" },
      { id: 2, path: "", name: "Faxriy bitiruvchilar" },
      { id: 3, path: "", name: "Bitiruvchilar to'g'risida ma'lumot" },
    ],
  },
];
